"""
sector_map.py — static ticker → GICS sector / industry lookup.

Covers all tickers in sp500_sample, nasdaq_sample, manual_default, and
seed lists (~260 tickers). No external API calls. Returns "Unknown" for
tickers not in the map — never raises.
"""
from __future__ import annotations

# Format: "TICKER": ("GICS Sector", "Industry Group / Sub-Industry")
_RAW: dict[str, tuple[str, str]] = {
    # ── Information Technology ───────────────────────────────────────────────
    "AAPL":  ("Information Technology", "Consumer Electronics"),
    "MSFT":  ("Information Technology", "Software"),
    "NVDA":  ("Information Technology", "Semiconductors"),
    "AVGO":  ("Information Technology", "Semiconductors"),
    "AMD":   ("Information Technology", "Semiconductors"),
    "TXN":   ("Information Technology", "Semiconductors"),
    "QCOM":  ("Information Technology", "Semiconductors"),
    "INTC":  ("Information Technology", "Semiconductors"),
    "MU":    ("Information Technology", "Semiconductors"),
    "MRVL":  ("Information Technology", "Semiconductors"),
    "NXPI":  ("Information Technology", "Semiconductors"),
    "ON":    ("Information Technology", "Semiconductors"),
    "MCHP":  ("Information Technology", "Semiconductors"),
    "AMAT":  ("Information Technology", "Semiconductor Equipment"),
    "LRCX":  ("Information Technology", "Semiconductor Equipment"),
    "KLAC":  ("Information Technology", "Semiconductor Equipment"),
    "SNPS":  ("Information Technology", "Electronic Design Automation"),
    "CDNS":  ("Information Technology", "Electronic Design Automation"),
    "CRM":   ("Information Technology", "Application Software"),
    "ORCL":  ("Information Technology", "Application Software"),
    "ADBE":  ("Information Technology", "Application Software"),
    "NOW":   ("Information Technology", "Application Software"),
    "INTU":  ("Information Technology", "Application Software"),
    "FICO":  ("Information Technology", "Application Software"),
    "ANSS":  ("Information Technology", "Application Software"),
    "PLTR":  ("Information Technology", "Application Software"),
    "SNOW":  ("Information Technology", "Application Software"),
    "OKTA":  ("Information Technology", "Application Software"),
    "TEAM":  ("Information Technology", "Application Software"),
    "HUBS":  ("Information Technology", "Application Software"),
    "DDOG":  ("Information Technology", "Application Software"),
    "BILL":  ("Information Technology", "Application Software"),
    "GTLB":  ("Information Technology", "Application Software"),
    "PATH":  ("Information Technology", "Application Software"),
    "MDB":   ("Information Technology", "Application Software"),
    "ESTC":  ("Information Technology", "Application Software"),
    "NCNO":  ("Information Technology", "Application Software"),
    "ALRM":  ("Information Technology", "Application Software"),
    "ASAN":  ("Information Technology", "Application Software"),
    "FROG":  ("Information Technology", "Application Software"),
    "CFLT":  ("Information Technology", "Application Software"),
    "BRZE":  ("Information Technology", "Application Software"),
    "SMAR":  ("Information Technology", "Application Software"),
    "BOX":   ("Information Technology", "Application Software"),
    "DRCT":  ("Information Technology", "Application Software"),
    "BLZE":  ("Information Technology", "Application Software"),
    "ZM":    ("Information Technology", "Application Software"),
    "DOCU":  ("Information Technology", "Application Software"),
    "APP":   ("Information Technology", "Application Software"),
    "PANW":  ("Information Technology", "Systems Software"),
    "CRWD":  ("Information Technology", "Systems Software"),
    "ZS":    ("Information Technology", "Systems Software"),
    "NET":   ("Information Technology", "Systems Software"),
    "CSCO":  ("Information Technology", "Communications Equipment"),
    "ANET":  ("Information Technology", "Communications Equipment"),
    "ACN":   ("Information Technology", "IT Consulting & Services"),
    "CTSH":  ("Information Technology", "IT Consulting & Services"),
    "EPAM":  ("Information Technology", "IT Consulting & Services"),
    "GDDY":  ("Information Technology", "Internet Services & Infrastructure"),
    "WIX":   ("Information Technology", "Internet Services & Infrastructure"),
    # ── Communication Services ───────────────────────────────────────────────
    "GOOGL": ("Communication Services", "Interactive Media & Services"),
    "META":  ("Communication Services", "Interactive Media & Services"),
    "NFLX":  ("Communication Services", "Movies & Entertainment"),
    "DIS":   ("Communication Services", "Movies & Entertainment"),
    "WBD":   ("Communication Services", "Movies & Entertainment"),
    "PARA":  ("Communication Services", "Movies & Entertainment"),
    "FOXA":  ("Communication Services", "Movies & Entertainment"),
    "ROKU":  ("Communication Services", "Broadcasting & Cable TV"),
    "SPOT":  ("Communication Services", "Interactive Media & Services"),
    "SNAP":  ("Communication Services", "Interactive Media & Services"),
    "PINS":  ("Communication Services", "Interactive Media & Services"),
    "RBLX":  ("Communication Services", "Interactive Home Entertainment"),
    "U":     ("Communication Services", "Interactive Home Entertainment"),
    "TTD":   ("Communication Services", "Advertising"),
    "OMC":   ("Communication Services", "Advertising"),
    "IPG":   ("Communication Services", "Advertising"),
    "T":     ("Communication Services", "Integrated Telecommunication Services"),
    "VZ":    ("Communication Services", "Integrated Telecommunication Services"),
    "TMUS":  ("Communication Services", "Wireless Telecommunication Services"),
    # ── Consumer Discretionary ───────────────────────────────────────────────
    "TSLA":  ("Consumer Discretionary", "Automobiles"),
    "AMZN":  ("Consumer Discretionary", "Internet Retail"),
    "MELI":  ("Consumer Discretionary", "Internet Retail"),
    "SHOP":  ("Consumer Discretionary", "Internet Retail"),
    "DASH":  ("Consumer Discretionary", "Internet Retail"),
    "BKNG":  ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    "ABNB":  ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    "NCLH":  ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    "CCL":   ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    "RCL":   ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    "MCD":   ("Consumer Discretionary", "Restaurants"),
    "SBUX":  ("Consumer Discretionary", "Restaurants"),
    "CMG":   ("Consumer Discretionary", "Restaurants"),
    "HD":    ("Consumer Discretionary", "Home Improvement Retail"),
    "LOW":   ("Consumer Discretionary", "Home Improvement Retail"),
    "TGT":   ("Consumer Discretionary", "General Merchandise Stores"),
    "NKE":   ("Consumer Discretionary", "Footwear"),
    "DKNG":  ("Consumer Discretionary", "Casinos & Gaming"),
    "PENN":  ("Consumer Discretionary", "Casinos & Gaming"),
    "MGM":   ("Consumer Discretionary", "Casinos & Gaming"),
    "WYNN":  ("Consumer Discretionary", "Casinos & Gaming"),
    "LVS":   ("Consumer Discretionary", "Casinos & Gaming"),
    "CZR":   ("Consumer Discretionary", "Casinos & Gaming"),
    "MAR":   ("Consumer Discretionary", "Hotels, Resorts & Cruise Lines"),
    # ── Consumer Staples ─────────────────────────────────────────────────────
    "PG":    ("Consumer Staples", "Household Products"),
    "KO":    ("Consumer Staples", "Beverages - Non-Alcoholic"),
    "PEP":   ("Consumer Staples", "Beverages - Non-Alcoholic"),
    "CELH":  ("Consumer Staples", "Beverages - Non-Alcoholic"),
    "COST":  ("Consumer Staples", "Hypermarkets & Super Centers"),
    "WMT":   ("Consumer Staples", "Hypermarkets & Super Centers"),
    "PM":    ("Consumer Staples", "Tobacco"),
    # ── Health Care ──────────────────────────────────────────────────────────
    "LLY":   ("Health Care", "Pharmaceuticals"),
    "JNJ":   ("Health Care", "Pharmaceuticals"),
    "MRK":   ("Health Care", "Pharmaceuticals"),
    "ABBV":  ("Health Care", "Pharmaceuticals"),
    "BMY":   ("Health Care", "Pharmaceuticals"),
    "PFE":   ("Health Care", "Pharmaceuticals"),
    "MRNA":  ("Health Care", "Biotechnology"),
    "BNTX":  ("Health Care", "Biotechnology"),
    "NVAX":  ("Health Care", "Biotechnology"),
    "REGN":  ("Health Care", "Biotechnology"),
    "VRTX":  ("Health Care", "Biotechnology"),
    "GILD":  ("Health Care", "Biotechnology"),
    "AMGN":  ("Health Care", "Biotechnology"),
    "SGEN":  ("Health Care", "Biotechnology"),
    "ALNY":  ("Health Care", "Biotechnology"),
    "BMRN":  ("Health Care", "Biotechnology"),
    "RARE":  ("Health Care", "Biotechnology"),
    "FOLD":  ("Health Care", "Biotechnology"),
    "ACAD":  ("Health Care", "Biotechnology"),
    "IONS":  ("Health Care", "Biotechnology"),
    "TMO":   ("Health Care", "Life Sciences Tools & Services"),
    "DHR":   ("Health Care", "Life Sciences Tools & Services"),
    "ABT":   ("Health Care", "Health Care Equipment"),
    "ISRG":  ("Health Care", "Health Care Equipment"),
    "SYK":   ("Health Care", "Health Care Equipment"),
    "BSX":   ("Health Care", "Health Care Equipment"),
    "MDT":   ("Health Care", "Health Care Equipment"),
    "UNH":   ("Health Care", "Managed Health Care"),
    "ELV":   ("Health Care", "Managed Health Care"),
    "CI":    ("Health Care", "Managed Health Care"),
    "HUM":   ("Health Care", "Managed Health Care"),
    "CVS":   ("Health Care", "Health Care Services"),
    "MCK":   ("Health Care", "Health Care Distributors"),
    "VEEV":  ("Health Care", "Health Care Technology"),
    # ── Financials ───────────────────────────────────────────────────────────
    "JPM":   ("Financials", "Diversified Banks"),
    "BAC":   ("Financials", "Diversified Banks"),
    "WFC":   ("Financials", "Diversified Banks"),
    "GS":    ("Financials", "Investment Banking & Brokerage"),
    "MS":    ("Financials", "Investment Banking & Brokerage"),
    "SCHW":  ("Financials", "Investment Banking & Brokerage"),
    "BLK":   ("Financials", "Asset Management & Custody Banks"),
    "SPGI":  ("Financials", "Financial Exchanges & Data"),
    "CME":   ("Financials", "Financial Exchanges & Data"),
    "ICE":   ("Financials", "Financial Exchanges & Data"),
    "NDAQ":  ("Financials", "Financial Exchanges & Data"),
    "COIN":  ("Financials", "Financial Exchanges & Data"),
    "V":     ("Financials", "Transaction & Payment Processing"),
    "MA":    ("Financials", "Transaction & Payment Processing"),
    "AXP":   ("Financials", "Consumer Finance"),
    "COF":   ("Financials", "Consumer Finance"),
    "SOFI":  ("Financials", "Consumer Finance"),
    "AFRM":  ("Financials", "Consumer Finance"),
    "UPST":  ("Financials", "Consumer Finance"),
    "HOOD":  ("Financials", "Investment Banking & Brokerage"),
    "AIG":   ("Financials", "Multi-line Insurance"),
    "PRU":   ("Financials", "Life & Health Insurance"),
    "MET":   ("Financials", "Life & Health Insurance"),
    "AFL":   ("Financials", "Life & Health Insurance"),
    "TRV":   ("Financials", "Property & Casualty Insurance"),
    "CB":    ("Financials", "Property & Casualty Insurance"),
    "PGR":   ("Financials", "Property & Casualty Insurance"),
    "AON":   ("Financials", "Insurance Brokers"),
    "MMC":   ("Financials", "Insurance Brokers"),
    "WTW":   ("Financials", "Insurance Brokers"),
    "AJG":   ("Financials", "Insurance Brokers"),
    "BRO":   ("Financials", "Insurance Brokers"),
    "BRK-B": ("Financials", "Multi-line Insurance"),
    # ── Industrials ──────────────────────────────────────────────────────────
    "GE":    ("Industrials", "Industrial Conglomerates"),
    "HON":   ("Industrials", "Industrial Conglomerates"),
    "MMM":   ("Industrials", "Industrial Conglomerates"),
    "CAT":   ("Industrials", "Construction Machinery & Heavy Equipment"),
    "DE":    ("Industrials", "Agricultural & Farm Machinery"),
    "RTX":   ("Industrials", "Aerospace & Defense"),
    "LMT":   ("Industrials", "Aerospace & Defense"),
    "BA":    ("Industrials", "Aerospace & Defense"),
    "NOC":   ("Industrials", "Aerospace & Defense"),
    "EMR":   ("Industrials", "Electrical Components & Equipment"),
    "ETN":   ("Industrials", "Electrical Components & Equipment"),
    "PH":    ("Industrials", "Industrial Machinery & Supplies"),
    "ITW":   ("Industrials", "Industrial Machinery & Supplies"),
    "UBER":  ("Industrials", "Ground Transportation"),
    "LDOS":  ("Industrials", "IT Consulting & Services"),
    "SAIC":  ("Industrials", "IT Consulting & Services"),
    "BAH":   ("Industrials", "IT Consulting & Services"),
    # ── Energy ───────────────────────────────────────────────────────────────
    "XOM":   ("Energy", "Oil & Gas Integrated"),
    "CVX":   ("Energy", "Oil & Gas Integrated"),
    "COP":   ("Energy", "Oil & Gas Exploration & Production"),
    "EOG":   ("Energy", "Oil & Gas Exploration & Production"),
    "OXY":   ("Energy", "Oil & Gas Exploration & Production"),
    "FANG":  ("Energy", "Oil & Gas Exploration & Production"),
    "SLB":   ("Energy", "Oil & Gas Equipment & Services"),
    "HAL":   ("Energy", "Oil & Gas Equipment & Services"),
    "MPC":   ("Energy", "Oil & Gas Refining & Marketing"),
    "VLO":   ("Energy", "Oil & Gas Refining & Marketing"),
    # ── Materials ────────────────────────────────────────────────────────────
    "FCX":   ("Materials", "Copper"),
    "NEM":   ("Materials", "Gold"),
    "AA":    ("Materials", "Aluminum"),
    "NUE":   ("Materials", "Steel"),
    "CF":    ("Materials", "Fertilizers & Agricultural Chemicals"),
    "MOS":   ("Materials", "Fertilizers & Agricultural Chemicals"),
    "LIN":   ("Materials", "Industrial Gases"),
    "APD":   ("Materials", "Industrial Gases"),
    "ECL":   ("Materials", "Specialty Chemicals"),
    "SHW":   ("Materials", "Specialty Chemicals"),
    # ── Utilities ────────────────────────────────────────────────────────────
    "NEE":   ("Utilities", "Electric Utilities"),
    "SO":    ("Utilities", "Electric Utilities"),
    "DUK":   ("Utilities", "Electric Utilities"),
    "AEP":   ("Utilities", "Electric Utilities"),
    "D":     ("Utilities", "Electric Utilities"),
    "EXC":   ("Utilities", "Electric Utilities"),
    "XEL":   ("Utilities", "Electric Utilities"),
    "PCG":   ("Utilities", "Electric Utilities"),
    "WEC":   ("Utilities", "Electric Utilities"),
    "SRE":   ("Utilities", "Multi-Utilities"),
    # ── Real Estate ──────────────────────────────────────────────────────────
    "PLD":   ("Real Estate", "Industrial REITs"),
    "AMT":   ("Real Estate", "Specialized REITs"),
    "OPEN":  ("Real Estate", "Real Estate Services"),
    "RDFN":  ("Real Estate", "Real Estate Services"),
    "REDFIN":("Real Estate", "Real Estate Services"),
}

# Compile to uppercase keys for O(1) lookup
_SECTOR_MAP: dict[str, dict[str, str]] = {
    ticker: {"sector": sec, "industry": ind}
    for ticker, (sec, ind) in _RAW.items()
}


def get_sector_info(ticker: str) -> dict[str, str]:
    """Return {sector, industry} for ticker. Never raises. Unknown → 'Unknown'."""
    return _SECTOR_MAP.get(ticker.upper().strip(),
                           {"sector": "Unknown", "industry": ""})


def sector_map_size() -> int:
    return len(_SECTOR_MAP)
